version: '3.5'

services:
  backend:
    container_name: todo-server
    restart: unless-stopped
    build:
      # src must be in context
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - internal-client
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGODB_URL=mongodb+srv://tan:abcdefg@cluster0.wrwhy.mongodb.net/todo
  
  frontend:
    container_name: todo-client
    restart: unless-stopped
    build:
      # src must be in context
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - internal-client
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL=http://52.147.197.64:5000

networks:
  default:
    name: mdp-default
  internal-client:
    name: frontend
